### ISSUE TITLE
What is your CPU?

### ISSUE THREAD

**Issue by longmalongma** [minzhang-1/PointHop#1]
Are you sure you can complete the online training in 20 minutes with CPU?How much is your CPU?
when I try to run your code,I meet this problem that ValueError: array must not contain infs or NaNs

**Comment by minzhang-1** [comment]
Yes, Intel(R)Xeon(R), combined with your question in PointHop++, I guess you might not have enough memory. My suggestion is to change multi threading into a single thread in PointHop++ if you want to run on laptop. For this work, you may try to increase batch number.

**Comment by longmalongma** [comment]
> Yes, Intel(R)Xeon(R), combined with your question in PointHop++, I guess you might not have enough memory. My suggestion is to change multi threading into a single thread in PointHop++ if you want to run on laptop. For this work, you may try to increase batch number.

thanks for your reply,I made it,where i find feat.pkl?

**Comment by minzhang-1** [comment]
There is no feat.pkl in this work. Why do you need that?

**Comment by longmalongma** [comment]
sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
    idx_save=None, new_xyz_save=None)
TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
i have try to set it ,but i fained,can you help me?

**Comment by minzhang-1** [comment]
> sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
> idx_save=None, new_xyz_save=None)
> TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
> i have try to set it ,but i fained,can you help me?

Sorry about that, I have updated evaluate.py.

**Comment by longmalongma** [comment]
> > sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
> > idx_save=None, new_xyz_save=None)
> > TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
> > i have try to set it ,but i fained,can you help me?
> 
> Sorry about that, I have updated evaluate.py.
Thank you, I have tried this before,but this problem appear:
/PointHop-master/point_utils.py", line 111, in knn
    idx_tmp = np.concatenate(idx, axis=0)
ValueError: need at least one array to concatenate
it at least need two array.

**Comment by minzhang-1** [comment]
> > > sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
> > > idx_save=None, new_xyz_save=None)
> > > TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
> > > i have try to set it ,but i fained,can you help me?
> > 
> > 
> > Sorry about that, I have updated evaluate.py.
> > Thank you, I have tried this before,but this problem appear:
> > /PointHop-master/point_utils.py", line 111, in knn
> > idx_tmp = np.concatenate(idx, axis=0)
> > ValueError: need at least one array to concatenate
> > it at least need two array.

You may download the new evaluate.py to see whether this happens. It works well in my computer now.

**Comment by longmalongma** [comment]
> > > > sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
> > > > idx_save=None, new_xyz_save=None)
> > > > TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
> > > > i have try to set it ,but i fained,can you help me?
> > > 
> > > 
> > > Sorry about that, I have updated evaluate.py.
> > > Thank you, I have tried this before,but this problem appear:
> > > /PointHop-master/point_utils.py", line 111, in knn
> > > idx_tmp = np.concatenate(idx, axis=0)
> > > ValueError: need at least one array to concatenate
> > > it at least need two array.
> 
> You may download the new evaluate.py to see whether this happens. It works well in my computer now.

I try to test it by your evaluate.py, the problem still exist, i can't find the reason,by the way,can your code merge with pytorch based code?

**Comment by minzhang-1** [comment]
> > > > > sorry,i forget to change the path of files,when i try to run python evaluate.py,i meet this prboblem: File "evaluate.py", line 73, in main
> > > > > idx_save=None, new_xyz_save=None)
> > > > > TypeError: pointhop_pred() missing 1 required positional argument: 'n_batch'
> > > > > i have try to set it ,but i fained,can you help me?
> > > > 
> > > > 
> > > > Sorry about that, I have updated evaluate.py.
> > > > Thank you, I have tried this before,but this problem appear:
> > > > /PointHop-master/point_utils.py", line 111, in knn
> > > > idx_tmp = np.concatenate(idx, axis=0)
> > > > ValueError: need at least one array to concatenate
> > > > it at least need two array.
> > 
> > 
> > You may download the new evaluate.py to see whether this happens. It works well in my computer now.
> 
> I try to test it by your evaluate.py, the problem still exist, i can't find the reason,by the way,can your code merge with pytorch based code?

I have tested the evaluate.py on my computer, it runs well. Please make sure you download the new one.

**Comment by longmalongma** [comment]
I made it,thanks for your help.
